CREATE TABLE IF NOT EXISTS users (
    `ID` INT(100) NOT NULL AUTOINCREMENT,
    `LOGIN` VARCHAR(255) NOT NULL,
    `PASSWORD` VARCHAR(255) NOT NULL,
    `COMMENT` TEXT,
    PRIMARY KEY (ID)
);

DROP TABLE IF EXISTS users;